worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    types {
        application/javascript js mjs;
        application/wasm wasm;
    }

    server {
        listen 8080;
        
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Resource-Policy "cross-origin" always;

        location /pdf/ {
            alias /usr/share/nginx/html/pdf/;
            try_files $uri $uri/ /pdf/index.html;
        }
    }
}
