worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    types {
        application/javascript mjs;
    }

    server {
        listen 8080;
        
        root /usr/share/nginx/html;
        
        # --- LES LIGNES MAGIQUES ANTI-REDIRECTION ---
        absolute_redirect off;
        port_in_redirect off;
        
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Resource-Policy "cross-origin" always;

        location = / {
            return 301 /pdf/;
        }

        location /pdf/ {
            try_files $uri $uri/ /pdf/index.html;
        }
    }
}
