worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # On ajoute uniquement l'extension .mjs manquante pour LibreOffice
    types {
        application/javascript mjs;
    }

    server {
        listen 8080;
        
        # La solution au bug 404 : On définit la racine de manière globale
        root /usr/share/nginx/html;
        
        # En-têtes de sécurité obligatoires
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Resource-Policy "cross-origin" always;

        # Redirection de courtoisie : Si Nginx reçoit une requête à la racine, il renvoie vers /pdf/
        location = / {
            return 301 /pdf/;
        }

        # Le routage de la Single Page Application
        location /pdf/ {
            try_files $uri $uri/ /pdf/index.html;
        }
    }
}
